services:
  uptimekuma:
    container_name: uptimekuma
    image: louislam/uptime-kuma:${UPTIMEKUMA_VERSION:-latest}
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.monitoring.entrypoints=websecure
      - traefik.http.services.monitoring.loadbalancer.server.port=3001
      - traefik.http.routers.monitoring.rule=Host(`${UPTIMEKUMA_DOMAIN}`)
      - traefik.http.routers.monitoring.tls=true
