services:
  uptimekuma:
    container_name: uptimekuma
    image: louislam/uptime-kuma:${UPTIMEKUMA_VERSION:-latest}
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
