services:
  pihole:
    container_name: pihole
    image: pihole/pihole:${PIHOLE_VERSION:-latest}
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 53:53/tcp
      - ${SERVER_HOST}:53:53/udp
    environment:
      - TZ=${TZ}
      - WEBPASSWORD=${PIHOLE_PASSWORD}
      - PIHOLE_DNS_=1.1.1.1;9.9.9.9
      - DNSSEC=true
      - DNSMASQ_LISTENING=all
    volumes:
      - ./data/etc-pihole:/etc/pihole
      - ./data/etc-dnsmasq.d:/etc/dnsmasq.d

