version: '3.8'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 5353:80/tcp
    environment:
      - TZ:'Europe/Madrid' # Default is UTC
      - WEBPASSWORD:${PIHOLE_PASSWORD}
    volumes:
      - ./data/etc-pihole:/etc/pihole
      - ./data/etc-dnsmasq.d:/etc/dnsmasq.d
