version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./data/conf/:/etc/traefik/conf/
      - ./data/logs/:/var/log/traefik/
      - ./data/certs/:/etc/traefik/certs/
