version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./data/conf/:/etc/traefik/conf/
      - ./data/logs/:/var/log/traefik/
      - ./data/certs/:/etc/traefik/certs/
    labels:
      - traefik.enable=true
      - traefik.http.routers.proxy.entrypoints=websecure
      - traefik.http.services.proxy.loadbalancer.server.port=8080
      - traefik.http.routers.proxy.rule=Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.proxy.tls=true
      - traefik.http.routers.proxy.tls.certresolver=staging
