services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: favonia/cloudflare-ddns:${CLOUDFLARE_DDNS_VERSION:-latest}
    restart: unless-stopped
    network_mode: bridge
    cap_add:
      - SETUID
      - SETGID
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
      - UPDATE_ON_START=true
      - DELETE_ON_STOP=true
      - IP6_PROVIDER=none
      - PROXIED=false  # True if you have a web server
      - CF_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAINS=${CLOUDFLARE_DOMAINS}
      - TZ=${TZ}
      - UPTIMEKUMA=${UTPIMEKUMA_PUSH_URL}
