services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:${HOMARR_VERSION:-latest}
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./data/configs:/app/data/configs
      - ./data/icons:/app/public/icons
      - ./data/data:/data
    environment:
      - DEFAULT_COLOR_SCHEME=dark
      - DISABLE_ANALYTICS=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.services.dashboard.loadbalancer.server.port=7575
      - traefik.http.routers.dashboard.rule=Host(`${HOMARR_DOMAIN}`)
      - traefik.http.routers.dashboard.tls=true
