version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD:${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE:${MARIADB_DATABASE}
