services:
  mariadb:
    container_name: mariadb
    image: mariadb:${MARIADB_VERSION:-latest}
    restart: unless-stopped
    network_mode: bridge
    ports:
      - ${MARIADB_PORT:-3306}:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
