services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:${PORTAINER_VERSION:-latest}
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
