version: '3.8'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 9443:9443
