services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:${PORTAINER_VERSION:-latest}
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.container.entrypoints=websecure
      - traefik.http.services.container.loadbalancer.server.port=9000
      - traefik.http.routers.container.rule=Host(`${PORTAINER_DOMAIN}`)
      - traefik.http.routers.container.tls=true
      - traefik.http.routers.container.tls.certresolver=staging
