services:
  wireguard:
    container_name: wireguard
    image: ghcr.io/wg-easy/wg-easy:${WIREGUARD_VERSION:-latest}
    restart: unless-stopped
    network_mode: bridge
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - ${WIREGUARD_PORT}:51820/udp
    environment:
      - WG_HOST=${WIREGUARD_HOST}
      - PASSWORD=${WIREGUARD_UI_PASSWORD}
      - WG_DEFAULT_DNS=${WIREGUARD_DNS}
      - UI_TRAFFIC_STATS=true
    volumes:
      - ./data:/etc/wireguard
    labels:
      - traefik.enable=true
      - traefik.http.routers.vpn.entrypoints=websecure
      - traefik.http.services.vpn.loadbalancer.server.port=51821
      - traefik.http.routers.vpn.rule=Host(`${WIREGUARD_DOMAIN}`)
      - traefik.http.routers.vpn.tls=true
