---
- name: Update APT Cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade System Packages
  become: true
  apt:
    upgrade: dist
    autoclean: yes
    autoremove: yes
    dpkg_options: 'force-confdef,force-confold'
  notify: 'Reboot If Required'
